import json, sys
sys.stdout.reconfigure(encoding='utf-8')

path = r'd:\Polythecninco di Milano\AFB_Lab\Ali\persona_pipeline.ipynb'
nb = json.load(open(path, encoding='utf-8'))

# ── Patch 1: pb-config — stratify on toxicity instead of sentiment ────────
OLD_STRATA = 'SENTIMENT_STRATA_COL       = "sentiment"   # column in sentiment_<platform>.parquet to stratify on'
NEW_STRATA = 'SENTIMENT_STRATA_COL       = "toxicity"    # column in sentiment_<platform>.parquet to stratify on'

for cell in nb['cells']:
    if cell['id'] == 'pb-config':
        src = ''.join(cell['source'])
        assert OLD_STRATA in src, f"strata pattern not found in pb-config"
        src = src.replace(OLD_STRATA, NEW_STRATA)
        compile(src, 'pb-config', 'exec')
        lines = src.split('\n')
        cell['source'] = [l + '\n' for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])
        print('patched pb-config (SENTIMENT_STRATA_COL -> toxicity)')
        break

# ── Patch 2: pb-label — noise back in the LLM prompt ─────────────────────
NEW_PB_LABEL_SRC = (
    '# LLM-label each cluster into a 6-key persona schema (noise included, flagged).\n'
    'from google.genai import types\n'
    '\n'
    '_real_summaries  = [s for s in pb_cluster_summaries if not s["is_noise"]]\n'
    '_noise_summary   = next((s for s in pb_cluster_summaries if s["is_noise"]), None)\n'
    '# All summaries go to LLM — noise is clearly flagged in the block text.\n'
    '_all_for_llm     = ([_noise_summary] if _noise_summary else []) + _real_summaries\n'
    '\n'
    'PB_NAMING_SYSTEM = (\n'
    '    "You are a strategic audience analyst for an Italian Instagram influencer agency.\\n"\n'
    '    "Commenters were clustered into behavioural macro-segments (UMAP + HDBSCAN). Each cluster is\\n"\n'
    '    "described by mean behavioural stats, a dominant room-vibe mix, and representative comments.\\n"\n'
    '    "\\n"\n'
    '    "NOISE CLUSTER: one cluster is labelled *** NOISE ***. These are HDBSCAN noise points —\\n"\n'
    '    "users too behaviourally scattered to fit any dense cluster. Do NOT simply call them\\n"\n'
    '    "NOISE_UNCLASSIFIED. Instead, examine their stats and comments carefully and give them a\\n"\n'
    '    "descriptive label that captures their dominant observable characteristics (e.g. erratic\\n"\n'
    '    "lurkers, one-off commenters, etc.). Make clear in the description that they lack cluster\\n"\n'
    '    "cohesion, but still characterise what they seem to be doing.\\n"\n'
    '    "\\n"\n'
    '    "LABEL BIAS WARNING: Do NOT default to positive or neutral personas. The dataset may contain\\n"\n'
    '    "critics, trolls, toxic commenters, or passive lurkers. If a cluster\'s stats show high\\n"\n'
    '    "toxicity_rate, high pct_negative, low word_count, or hostile comment fragments, label it\\n"\n'
    '    "accordingly (e.g. CRITICAL_DETRACTOR, TOXIC_TROLL, PASSIVE_LURKER). Be honest and\\n"\n'
    '    "comprehensive — the full spectrum of audience behaviour must be represented.\\n"\n'
    '    "\\n"\n'
    '    "Turn every cluster into ONE audience persona. Personas must be MUTUALLY EXCLUSIVE.\\n"\n'
    f'    f"Return exactly {{len(_all_for_llm)}} personas ordered by audience share (largest first).\\n"\n'
    '    "For each persona output exactly these 6 keys:\\n"\n'
    '    "  codename (UPPER_SNAKE_CASE),\\n"\n'
    '    "  label (short Title Case, 2-4 words),\\n"\n'
    '    "  description (1-2 sentences — who they are and what drives their engagement),\\n"\n'
    '    "  quantitative_signals (3-5 distinguishing behavioural signals as strings),\\n"\n'
    '    "  example_comments (2-3 verbatim fragments drawn from the cluster\'s sample comments),\\n"\n'
    '    "  labeling_rationale (1-2 sentences: WHY this label — which stats or comment patterns\\n"\n'
    '    "    were decisive, and what distinguishes it from adjacent clusters).\\n"\n'
    '    "Output ONLY a valid JSON array of objects with exactly those 6 keys. No preamble, no markdown fences."\n'
    ')\n'
    '\n'
    'def _pb_block(s):\n'
    '    stats = "  ".join(f"{k}={v:.2f}" if isinstance(v, float) else f"{k}={v}"\n'
    '                      for k, v in s["mean_behavioral_stats"].items())\n'
    '    vibe = "  ".join(f"{k}: {v}%" for k, v in s["dominant_room_vibe_mix"].items())\n'
    '    comments = "\\n    - ".join(s["sample_comments"][:8])\n'
    '    noise_tag = "  *** NOISE — low-cohesion, no dominant pattern ***" if s["is_noise"] else ""\n'
    '    return (f"CLUSTER {s[\'cluster_id\']}{noise_tag}  (n={s[\'n_users\']:,}, {s[\'pct_audience\']}% of all users)\\n"\n'
    '            f"  Mean behavioural stats: {stats}\\n"\n'
    '            f"  Dominant room-vibe mix: {vibe}\\n"\n'
    '            f"  Sample comments:\\n    - {comments}")\n'
    '\n'
    'pb_prompt = PB_NAMING_SYSTEM + "\\n\\n=== CLUSTER DATA ===\\n\\n" + "\\n\\n".join(\n'
    '    _pb_block(s) for s in _all_for_llm)\n'
    '\n'
    'pb_cfg = types.GenerateContentConfig(\n'
    '    temperature=0.0, top_p=1.0, max_output_tokens=8192,\n'
    '    response_mime_type="application/json",\n'
    '    thinking_config=types.ThinkingConfig(thinking_budget=4096),\n'
    ')\n'
    'print(f"Labelling {len(_all_for_llm)} clusters via {MODEL_STAGE3_NAMING} (noise included + flagged) ...")\n'
    'pb_resp = client.models.generate_content(model=MODEL_STAGE3_NAMING, contents=pb_prompt, config=pb_cfg)\n'
    '\n'
    '_pb_text = strip_fences(pb_resp.text or "")\n'
    'try:\n'
    '    pb_macro_personas = json.loads(_pb_text)\n'
    'except Exception as e:\n'
    '    print("Could not parse LLM output:", str(e)[:120], "\\n", _pb_text[:400])\n'
    '    pb_macro_personas = []\n'
    '\n'
    '_keys = ["codename", "label", "description", "quantitative_signals", "example_comments", "labeling_rationale"]\n'
    'pb_macro_personas = [{k: p.get(k, "" if k in ("codename","label","description","labeling_rationale") else [])\n'
    '                      for k in _keys}\n'
    '                     for p in pb_macro_personas if isinstance(p, dict)][:TARGET_PERSONAS]\n'
    '\n'
    'print(f"\\n{len(pb_macro_personas)} personas from Pathway B:")\n'
    'for p in pb_macro_personas:\n'
    '    is_noise = p["codename"] == "NOISE_UNCLASSIFIED"\n'
    '    tag = " [NOISE]" if is_noise else ""\n'
    '    print(f"   {str(p[\'codename\']):<30}{tag}  | {p[\'label\']}")\n'
    '    if p.get("labeling_rationale"):\n'
    '        print(f"      rationale: {p[\'labeling_rationale\'][:120]}")\n'
    '\n'
    'import os\n'
    'if os.path.exists(TAXONOMY_JSON_PATH):\n'
    '    data = json.load(open(TAXONOMY_JSON_PATH, encoding="utf-8"))\n'
    'else:\n'
    '    data = {"status": "PENDING_HUMAN_REVIEW", "raw_candidates": []}\n'
    'data["final_taxonomy"] = pb_macro_personas\n'
    'data["status"] = "PENDING_HUMAN_REVIEW"\n'
    'data["pathway"] = "B_CLUSTER"\n'
    'data["instructions"] = ("Pathway B (UMAP+HDBSCAN) taxonomy. Review/merge, ensure MECE, "\n'
    '                        "set status=\'APPROVED\' before Stage 2. Set CONSOLIDATION_PATHWAY=\'B_CLUSTER\' "\n'
    '                        "so the Pathway A wrapper cell does not overwrite this.")\n'
    'with open(TAXONOMY_JSON_PATH, "w", encoding="utf-8") as f:\n'
    '    json.dump(data, f, ensure_ascii=False, indent=2)\n'
    'print(f"\\nWritten -> {TAXONOMY_JSON_PATH} (pathway=B_CLUSTER). "\n'
    '      "Set CONSOLIDATION_PATHWAY=\'B_CLUSTER\' and status=\'APPROVED\' before Stage 2.")\n'
    '\n'
    '# cluster_id -> codename map (covers -1 for noise).\n'
    '_cluster_map = {int(s["cluster_id"]): pb_macro_personas[i]["codename"]\n'
    '                for i, s in enumerate(pb_cluster_summaries) if i < len(pb_macro_personas)}\n'
    'with open(CLUSTER_PERSONA_MAP_PATH, "w", encoding="utf-8") as f:\n'
    '    json.dump(_cluster_map, f, ensure_ascii=False, indent=2)\n'
    'pb_df[["author_id", "macro_cluster"]].to_parquet(\n'
    '    f"{LOCAL_DIR}/pathway_b_assignments_{PLATFORM}.parquet", index=False)\n'
    'print(f"Cluster->persona map -> {CLUSTER_PERSONA_MAP_PATH}; "\n'
    '      f"assignments -> pathway_b_assignments_{PLATFORM}.parquet")\n'
)

compile(NEW_PB_LABEL_SRC, 'pb-label', 'exec')
print('pb-label syntax OK')

for cell in nb['cells']:
    if cell['id'] == 'pb-label':
        lines = NEW_PB_LABEL_SRC.split('\n')
        cell['source'] = [l + '\n' for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])
        print('patched pb-label (noise back in LLM)')
        break

# ── Patch 3: pb-sentiment-persona-plots — toxic share of ALL toxic users ──
# Key change: toxicity charts show what % of ALL toxic users (across the whole
# dataset) ended up in each cluster/persona — i.e., how toxic users are
# distributed across personas, not the internal toxicity rate of a persona.
NEW_SENT_PLOTS_SRC = (
    'import pandas as pd\n'
    'import matplotlib.pyplot as plt\n'
    'import matplotlib.ticker as mticker\n'
    'import numpy as np\n'
    'import json, os\n'
    '\n'
    '# ── load data ──────────────────────────────────────────────────────────────\n'
    '_pb = pd.read_parquet(f"{LOCAL_DIR}/pathway_b_assignments_{PLATFORM}.parquet")\n'
    '_pb["author_id"] = _pb["author_id"].astype(str)\n'
    '\n'
    '_sent_raw = pd.read_parquet(SENTIMENT_PATH)\n'
    'if "author_id" not in _sent_raw.columns:\n'
    '    raise ValueError("sentiment parquet lacks author_id — join via comment_id first")\n'
    '_sent_raw["author_id"] = _sent_raw["author_id"].astype(str)\n'
    '\n'
    '# dominant sentiment per user\n'
    '_dom_sent = (_sent_raw.groupby("author_id")["sentiment"]\n'
    '              .agg(lambda x: x.value_counts().idxmax())\n'
    '              .reset_index()\n'
    '              .rename(columns={"sentiment": "dominant_sentiment"}))\n'
    '\n'
    '# dominant toxicity per user\n'
    '_has_tox = "toxicity" in _sent_raw.columns\n'
    'if _has_tox:\n'
    '    _dom_tox = (_sent_raw.groupby("author_id")["toxicity"]\n'
    '                .agg(lambda x: x.value_counts().idxmax())\n'
    '                .reset_index()\n'
    '                .rename(columns={"toxicity": "dominant_toxicity"}))\n'
    '    # is_toxic_user: at least one comment flagged mild or severe\n'
    '    _user_any_tox = (_sent_raw.assign(\n'
    '        _tox_flag=_sent_raw["toxicity"].isin(["mild", "severe"])\n'
    '    ).groupby("author_id")["_tox_flag"].any()\n'
    '     .reset_index().rename(columns={"_tox_flag": "is_toxic_user"}))\n'
    '\n'
    '_cmap = json.load(open(CLUSTER_PERSONA_MAP_PATH, encoding="utf-8"))\n'
    '_cmap_int = {int(k): v for k, v in _cmap.items()}\n'
    '\n'
    '_df = _pb.merge(_dom_sent, on="author_id", how="left")\n'
    'if _has_tox:\n'
    '    _df = _df.merge(_dom_tox, on="author_id", how="left")\n'
    '    _df = _df.merge(_user_any_tox, on="author_id", how="left")\n'
    '    _df["is_toxic_user"] = _df["is_toxic_user"].fillna(False)\n'
    'else:\n'
    '    _df["dominant_toxicity"] = "unknown"\n'
    '    _df["is_toxic_user"] = False\n'
    '\n'
    '_df["persona"] = _df["macro_cluster"].map(_cmap_int).fillna("UNKNOWN")\n'
    '# keep NOISE in df but label it; exclude from per-persona breakdowns below\n'
    '_df_all  = _df.copy()\n'
    '_df_real = _df[_df["macro_cluster"] != -1].copy()\n'
    '\n'
    'os.makedirs(f"{LOCAL_DIR}/figs", exist_ok=True)\n'
    '\n'
    'SENT_ORDER  = ["negative", "neutral", "positive"]\n'
    'SENT_COLORS = {"negative": "#d62728", "neutral": "#aec7e8", "positive": "#2ca02c"}\n'
    'TOX_ORDER   = ["none", "mild", "severe", "spam_promo"]\n'
    'TOX_COLORS  = {"none": "#9ecae1", "mild": "#fdae6b", "severe": "#d62728", "spam_promo": "#756bb1"}\n'
    '\n'
    '# ── figure 1: stacked 100% bar — sentiment mix per persona ────────────────\n'
    '_ct_sent = (_df_real.dropna(subset=["dominant_sentiment"])\n'
    '            .groupby(["persona", "dominant_sentiment"])\n'
    '            .size().unstack(fill_value=0)\n'
    '            .reindex(columns=[c for c in SENT_ORDER\n'
    '                              if c in _df_real["dominant_sentiment"].dropna().unique()],\n'
    '                     fill_value=0))\n'
    '_pct_sent = _ct_sent.div(_ct_sent.sum(axis=1), axis=0) * 100\n'
    '_pct_sent = _pct_sent.loc[_ct_sent.sum(axis=1).sort_values(ascending=False).index]\n'
    '\n'
    'fig1, ax1 = plt.subplots(figsize=(11, 5))\n'
    'bottom = pd.Series(0.0, index=_pct_sent.index)\n'
    'for sent in [c for c in SENT_ORDER if c in _pct_sent.columns]:\n'
    '    ax1.bar(_pct_sent.index, _pct_sent[sent], bottom=bottom,\n'
    '            label=sent.capitalize(), color=SENT_COLORS[sent], alpha=0.88)\n'
    '    bottom += _pct_sent[sent]\n'
    'ax1.set_title("Sentiment Mix per Persona (% of each persona\'s users)", fontsize=13, pad=10)\n'
    'ax1.set_xlabel("Persona (sorted by size)")\n'
    'ax1.set_ylabel("% of users in persona")\n'
    'ax1.set_ylim(0, 100)\n'
    'ax1.legend(title="Dominant sentiment", loc="upper right", fontsize=9)\n'
    'plt.xticks(rotation=35, ha="right", fontsize=9)\n'
    'plt.tight_layout()\n'
    'plt.savefig(f"{LOCAL_DIR}/figs/persona_sentiment_mix.png", dpi=150)\n'
    'plt.show()\n'
    'print("saved persona_sentiment_mix.png")\n'
    '\n'
    '# ── figure 2: where do ALL negative users land? (share of total negatives) ─\n'
    '_neg_users = _df_real[_df_real["dominant_sentiment"] == "negative"]\n'
    '_total_neg = max(len(_neg_users), 1)\n'
    '_neg_dist  = _neg_users.groupby("persona").size().sort_values(ascending=False)\n'
    '_neg_pct   = (_neg_dist / _total_neg * 100)\n'
    '\n'
    'fig2, ax2 = plt.subplots(figsize=(10, 5))\n'
    'ax2.bar(_neg_pct.index, _neg_pct.values, color=SENT_COLORS["negative"], alpha=0.85)\n'
    'ax2.set_title(\n'
    '    f"Where Do Negative Users Land? (share of all {_total_neg:,} negative-dominant users)",\n'
    '    fontsize=12, pad=10)\n'
    'ax2.set_xlabel("Persona")\n'
    'ax2.set_ylabel("% of ALL negative users")\n'
    'ax2.yaxis.set_major_locator(mticker.MaxNLocator(integer=False))\n'
    'for bar, pct in zip(ax2.patches, _neg_pct.values):\n'
    '    ax2.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n'
    '             f"{pct:.1f}%", ha="center", va="bottom", fontsize=8)\n'
    'plt.xticks(rotation=35, ha="right", fontsize=9)\n'
    'plt.tight_layout()\n'
    'plt.savefig(f"{LOCAL_DIR}/figs/persona_negative_dist.png", dpi=150)\n'
    'plt.show()\n'
    'print("saved persona_negative_dist.png")\n'
    '\n'
    '# ── figures 3-5: toxicity charts ──────────────────────────────────────────\n'
    'if _has_tox:\n'
    '    # figure 3: stacked 100% bar — toxicity mix within each persona\n'
    '    _ct_tox = (_df_real.dropna(subset=["dominant_toxicity"])\n'
    '               .groupby(["persona", "dominant_toxicity"])\n'
    '               .size().unstack(fill_value=0)\n'
    '               .reindex(columns=[c for c in TOX_ORDER\n'
    '                                 if c in _df_real["dominant_toxicity"].dropna().unique()],\n'
    '                        fill_value=0))\n'
    '    _pct_tox = _ct_tox.div(_ct_tox.sum(axis=1), axis=0) * 100\n'
    '    _pct_tox = _pct_tox.loc[_ct_tox.sum(axis=1).sort_values(ascending=False).index]\n'
    '\n'
    '    fig3, ax3 = plt.subplots(figsize=(11, 5))\n'
    '    bot3 = pd.Series(0.0, index=_pct_tox.index)\n'
    '    for tox in [c for c in TOX_ORDER if c in _pct_tox.columns]:\n'
    '        ax3.bar(_pct_tox.index, _pct_tox[tox], bottom=bot3,\n'
    '                label=tox.replace("_", " ").capitalize(),\n'
    '                color=TOX_COLORS.get(tox, "#aaaaaa"), alpha=0.88)\n'
    '        bot3 += _pct_tox[tox]\n'
    '    ax3.set_title("Toxicity Mix per Persona (% of each persona\'s users)", fontsize=13, pad=10)\n'
    '    ax3.set_xlabel("Persona (sorted by size)")\n'
    '    ax3.set_ylabel("% of users in persona")\n'
    '    ax3.set_ylim(0, 100)\n'
    '    ax3.legend(title="Dominant toxicity", loc="upper right", fontsize=9)\n'
    '    plt.xticks(rotation=35, ha="right", fontsize=9)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(f"{LOCAL_DIR}/figs/persona_toxicity_mix.png", dpi=150)\n'
    '    plt.show()\n'
    '    print("saved persona_toxicity_mix.png")\n'
    '\n'
    '    # figure 4: where do ALL toxic users land? (share of total toxic users per persona)\n'
    '    _tox_users  = _df_real[_df_real["is_toxic_user"] == True]\n'
    '    _total_tox  = max(len(_tox_users), 1)\n'
    '    _tox_dist   = _tox_users.groupby("persona").size().sort_values(ascending=False)\n'
    '    _tox_pct    = _tox_dist / _total_tox * 100\n'
    '\n'
    '    fig4, ax4 = plt.subplots(figsize=(10, 5))\n'
    '    bars = ax4.bar(_tox_pct.index, _tox_pct.values,\n'
    '                   color="#d62728", alpha=0.82)\n'
    '    ax4.set_title(\n'
    '        f"Where Do Toxic Users Land? (share of all {_total_tox:,} toxic users)",\n'
    '        fontsize=12, pad=10)\n'
    '    ax4.set_xlabel("Persona")\n'
    '    ax4.set_ylabel("% of ALL toxic users")\n'
    '    for bar, pct in zip(bars, _tox_pct.values):\n'
    '        ax4.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.3,\n'
    '                 f"{pct:.1f}%", ha="center", va="bottom", fontsize=8)\n'
    '    plt.xticks(rotation=35, ha="right", fontsize=9)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(f"{LOCAL_DIR}/figs/persona_toxic_dist.png", dpi=150)\n'
    '    plt.show()\n'
    '    print("saved persona_toxic_dist.png")\n'
    '\n'
    '    # figure 5: toxic vs non-toxic users — proportional breakdown per persona\n'
    '    _tox_ct = (_df_real.groupby("persona")["is_toxic_user"]\n'
    '               .value_counts().unstack(fill_value=0)\n'
    '               .rename(columns={True: "toxic", False: "non-toxic"})\n'
    '               .reindex(columns=["non-toxic", "toxic"], fill_value=0))\n'
    '    _tox_ct_pct = _tox_ct.div(_tox_ct.sum(axis=1), axis=0) * 100\n'
    '    _tox_ct_pct = _tox_ct_pct.loc[_tox_ct.sum(axis=1).sort_values(ascending=False).index]\n'
    '\n'
    '    fig5, ax5 = plt.subplots(figsize=(11, 4))\n'
    '    ax5.bar(_tox_ct_pct.index, _tox_ct_pct.get("non-toxic", 0),\n'
    '            label="Non-toxic", color="#9ecae1", alpha=0.88)\n'
    '    ax5.bar(_tox_ct_pct.index, _tox_ct_pct.get("toxic", 0),\n'
    '            bottom=_tox_ct_pct.get("non-toxic", 0),\n'
    '            label="Toxic (mild+severe)", color="#d62728", alpha=0.88)\n'
    '    ax5.set_title("Toxic vs Non-Toxic User Split per Persona (%)", fontsize=13, pad=10)\n'
    '    ax5.set_xlabel("Persona (sorted by size)")\n'
    '    ax5.set_ylabel("% of users in persona")\n'
    '    ax5.set_ylim(0, 100)\n'
    '    ax5.legend(loc="upper right", fontsize=9)\n'
    '    plt.xticks(rotation=35, ha="right", fontsize=9)\n'
    '    plt.tight_layout()\n'
    '    plt.savefig(f"{LOCAL_DIR}/figs/persona_toxic_split.png", dpi=150)\n'
    '    plt.show()\n'
    '    print("saved persona_toxic_split.png")\n'
    'else:\n'
    '    print("No toxicity column found — skipping toxicity charts.")\n'
    '\n'
    '# ── summary table ──────────────────────────────────────────────────────────\n'
    'print(f"\\nPersona  |  total  |  neg%  |  pos%  |  toxic% (of persona)  |  toxic% (of all toxic)")\n'
    'print("-" * 80)\n'
    '_total_tox_all = max(int(_df_real["is_toxic_user"].sum()), 1) if _has_tox else 1\n'
    'for p in _pct_sent.index:\n'
    '    total = int(_ct_sent.loc[p].sum())\n'
    '    neg_pct = _pct_sent.loc[p].get("negative", 0)\n'
    '    pos_pct = _pct_sent.loc[p].get("positive", 0)\n'
    '    if _has_tox and p in _tox_ct.index:\n'
    '        tox_internal = float(_tox_ct.loc[p].get("toxic", 0) / max(_tox_ct.loc[p].sum(), 1) * 100)\n'
    '        tox_share    = float(_tox_ct.loc[p].get("toxic", 0) / _total_tox_all * 100)\n'
    '    else:\n'
    '        tox_internal = tox_share = 0.0\n'
    '    print(f"  {p:<32s} {total:5d}  {neg_pct:5.1f}%  {pos_pct:5.1f}%  "\n'
    '          f"{tox_internal:6.1f}%                {tox_share:6.1f}%")\n'
)

compile(NEW_SENT_PLOTS_SRC, 'pb-sentiment-persona-plots', 'exec')
print('pb-sentiment-persona-plots syntax OK')

for cell in nb['cells']:
    if cell['id'] == 'pb-sentiment-persona-plots':
        lines = NEW_SENT_PLOTS_SRC.split('\n')
        cell['source'] = [l + '\n' for l in lines[:-1]] + ([lines[-1]] if lines[-1] else [])
        print('patched pb-sentiment-persona-plots')
        break

# ── Update markdown header ─────────────────────────────────────────────────
for cell in nb['cells']:
    if cell['id'] == 'pb-sentiment-analysis-header':
        cell['source'] = [
            '## Persona × Sentiment & Toxicity Analysis\n',
            '\n',
            'These charts show how **sentiment** and **toxicity** distribute across personas:\n',
            '\n',
            '- **Sentiment mix**: what fraction of each persona\'s users are negative/neutral/positive\n',
            '- **Where do negative users land**: which personas capture the most negative-dominant users (% of all negatives)\n',
            '- **Toxicity mix**: internal toxicity breakdown within each persona\n',
            '- **Where do toxic users land**: which personas capture the most toxic users (% of all toxic users)\n',
            '- **Toxic vs non-toxic split**: proportion of toxic users within each persona\n',
            '\n',
            'NOISE_UNCLASSIFIED users are excluded from all charts.\n',
        ]
        print('patched pb-sentiment-analysis-header')
        break

with open(path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print('saved')
