
from __future__ import annotations
from typing import Literal, Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Pydantic v2 response models — single source of truth for:
#   1. responseSchema in every JSONL line (get_batch_generation_config_dict)
#   2. System-prompt schema strings (auto-generated by _model_to_prompt_schema)
# ---------------------------------------------------------------------------

class SentimentItem(BaseModel):
    i:         int
    sentiment: Literal["positive", "negative", "neutral", "mixed"]
    score:     float = Field(..., ge=-1.0, le=1.0,
                             description="-1.0 very negative .. 1.0 very positive")
    emotion:   Literal["joy", "trust", "fear", "surprise",
                       "sadness", "disgust", "anger", "anticipation", "neutral"]
    intensity: Literal["low", "medium", "high"]
    sarcasm:   bool
    toxicity:  Literal["none", "mild", "severe"]
    intent:    Literal["praise", "affection", "support", "criticism",
                       "question", "suggestion", "tag_share", "spam_promo", "joke", "other"]
    target:    Literal["creator", "appearance", "content_work", "product",
                       "other_user", "off_topic", "none"]
    lang:      str = Field(..., description="ISO-639-1 code, e.g. it, en")


class RoomRead(BaseModel):
    vibe:                  Literal["celebratory", "supportive", "appreciative", "amused",
                                   "mixed", "debated", "divided", "critical",
                                   "hostile", "spam_heavy", "neutral"]
    consensus:             float = Field(..., ge=0.0, le=1.0)
    alignment:             float = Field(..., ge=-1.0, le=1.0)
    controversy:           float = Field(..., ge=0.0, le=1.0)
    sponsorship_alignment: float = Field(..., ge=0.0, le=1.0)
    split_axis:            Optional[str] = Field(None, description="<=5 words or null")
    dominant_stance:       str
    summary:               str


class SentimentResponse(BaseModel):
    req:   str
    items: list[SentimentItem]
    room:  RoomRead


def _sanitize_schema(schema: dict) -> dict:
    """
    Vertex AI responseSchema follows OpenAPI 3.0 subset and does NOT resolve
    $ref/$defs inline.  Pydantic v2 emits $defs for nested models; flatten them
    so every property is self-contained before embedding in the JSONL line.
    """
    defs = schema.pop("$defs", {})

    def _resolve(node):
        if isinstance(node, dict):
            if "$ref" in node:
                ref_name = node["$ref"].split("/")[-1]
                return _resolve(defs.get(ref_name, node))
            return {k: _resolve(v) for k, v in node.items()
                    if k not in ("title", "$schema")}
        if isinstance(node, list):
            return [_resolve(v) for v in node]
        return node

    return _resolve(schema)


def get_batch_generation_config_dict(
    response_model: type[BaseModel],
    max_tokens: int,
    thinking_budget: int | None = None,
) -> dict:
    """
    Returns a fully-serializable generationConfig dict for one Vertex Batch JSONL line.

    Vertex REST API spec:
      generationConfig.responseSchema   -- OpenAPI 3.0 schema object (flattened, no $defs)
      generationConfig.responseMimeType -- must be "application/json" when schema is set
    """
    raw_schema   = response_model.model_json_schema()
    clean_schema = _sanitize_schema(raw_schema)

    cfg: dict = {
        "temperature":      TEMPERATURE,
        "topP":             TOP_P,
        "maxOutputTokens":  max_tokens,
        "responseMimeType": "application/json",
        "responseSchema":   clean_schema,
    }
    if thinking_budget is not None:
        cfg["thinkingConfig"] = {"thinkingBudget": thinking_budget}
    return cfg


print("Pydantic response models + get_batch_generation_config_dict() ready.")
